FROM node:10-alpine
MAINTAINER Xeltor

LABEL h265ize_version="bleading edge" architecture="amd64"

RUN apk add --no-cache --update-cache git ffmpeg curl && \
    npm install Xeltor/h265ize --global --no-optional && \
    mkdir /watch

WORKDIR /h265ize

ENTRYPOINT ["/usr/local/bin/h265ize"]
